### ISSUE TITLE
Raspberry Pi 5 version

### ISSUE THREAD

**Issue by shadowofdarkness** [akkera102/gba_01_multiboot#3]
I didn't think this would be a issue so fast after the last update you made but apparently the Raspberry Pi 5 uses a new chipset to control the GPIO pins and the old libraries are not compatible. Would you be willing to make a new version of multiboot and sendsave to work on newer systems?
From my quick research it looks like only two options exist for the Pi 5 libgpiod and gpiozero ( which if I read right the gpiozero is the only one that works on all models)

I found a quick comparison article about them to help choose. Although I think you may need libgpiod as according to the article it is c but the other is pure python.

https://adafruit-playground.com/u/MakerMelissa/pages/comparing-libgpiod-and-gpiozero-speeds-on-the-raspberry-pi-5

**Comment by akkera102** [comment]
Hello, it's been a long time.

Raspberry Pi 5 learned from your information about controlling his GPIO pins. Every year, I find it difficult to keep up with the changing times.

Now, regarding the creation of new versions of multiboot and sendsave, I have determined that this is not necessary. That's because wiring pi is back. The source code has been handed over from Gordon to another person and development continues. Version 3.0 officially supports Pi 5. Great job!
https://github.com/WiringPi/WiringPi/releases

Therefore, I feel that rewriting my source code is unnecessary.

**Comment by shadowofdarkness** [comment]
Wow I didn't know that WiringPi is back. In all my Googling about the Pi 5 that was not mentioned. I'll give it a try.

**Comment by shadowofdarkness** [comment]
Thanks I can confirm it works I just tested both multiboot and sendsave (to backup a save) on my Pi 5 using WiringPi

What would be nice though is updating the README as I had to go back through the git commits to remember the exact gcc command to compile it with WiringPi.

**Comment by akkera102** [comment]
I am grateful for your advice. Updated readme.txt with commands for wiringPI.
